name: GitHub Actions Demo
on: [push]
jobs:
  lint_psalm_phpinsights_snifer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-site-lesson
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2

      - name: Composer Cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-dev-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-dev-${{ hashFiles('composer.lock') }}
            composer-dev-
      - name: Composer Install Dev
        run: |
          composer install
      - uses: overtrue/phplint@8.0
        with:
          path: .
          options: --exclude=*.log
      - name: phpinsights job
        run: ./vendor/bin/phpinsights -n
      - name: Sniffer job
        run: |
          composer check-style
          composer fix-style
